[project]
name = "conferences"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "dulwich>=1.2.4",
  "flask",
  "flask>=3.1.3",
  "lxml",
  "python-dateutil",
  "python-frontmatter>=1.3.0",
  "requests",
  "unidecode",
  "tzdata>=2026.3",
]

[dependency-groups]
dev = [
  # "ipdb",
]

[tool.vercel]
entrypoint = "conferences.pycon2026.shed:app"
