[project]
name = "conferences"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "dulwich>=1.2.4",
  "flask",
  "flask>=3.1.3",
  "lxml>=6",
  "pydantic==2.13.0b1",
  "pydantic-core==2.42.0",
  "python-dateutil",
  "python-frontmatter>=1.3.0",
  "requests",
  "rich>=15.0.0",
  "types-lxml>=2026.2.16",
  "tzdata>=2026.3",
  "unidecode",
]

[dependency-groups]
dev = [
  # "ipdb",
]

[tool.uv.sources]
pydantic-core = { path = "/data/data/com.termux/files/home/.cache/tinstall/wheelhouse/pydantic-core/pydantic_core-2.42.0-cp314-cp314-android_24_arm64_v8a.whl" }

[tool.vercel]
entrypoint = "conferences.pycon2026.shed:app"
